DROP DATABASE IF EXISTS taskmaster;
CREATE DATABASE taskmaster;
USE taskmaster;

DROP TABLE IF EXISTS tasks;
CREATE TABLE tasks (
    id INTEGER AUTO_INCREMENT,
    text VARCHAR(100) NOT NULL,
    state INTEGER,
    PRIMARY KEY (id)
);